// Data for Skydevaaben redirects
window.songs = ['acn', 'blcn', 'blswi', 'blswv', 'bace', 'bacn', 'baswi', 'skdh', 'fwaf', 'glp', 'lwy', 'afla', 'aflce', 'aflcn', 'aflec', 'plai', 'plce', 'plcn', 'plee', 'plpe'];
window.songNames = { 'acn': 'All Clear Now', 'bace': 'Born Again (Crimson Echo)', 'bacn': 'Born Again (Crimson Noise)', 'baswi': 'Born Again (Synthwave Instrumental)', 'blcn': 'Bleeding (Crimson Noise)', 'blswi': 'Bleeding (Synthwave Instrumental)', 'blswv': 'Bleeding (Synthwave Vocal)', 'fwaf': 'Fire Without a Flame', 'glp': 'Glass People', 'lwy': 'Lost Without You Lucid', 'plai': 'Please (Afterimage)', 'plce': 'Please (Crimson Echo)', 'plcn': 'Please (Crimson Noise)', 'plee': 'Please (Echoexe)', 'plpe': 'Please (Pleaexe)', 'aflcn': 'Low (Crimson Noise)', 'aflce': 'Low (Crimson Echo)', 'afla': 'Low (Annihilate)', 'aflec': 'Low (End Credits)', 'skdh': 'Digital Heartbeat' };
window.songArtists = {
  'acn': 'Sky.AI',
  'fwaf': 'Sky.AI',
  'lwy': 'Sky.AI',
  'glp': 'Sky.AI',
  'skdh': 'Skydevaaben',
  'bace': 'After Brügge',
  'bacn': 'After Brügge',
  'baswi': 'After Brügge',
  'blcn': 'After Brügge',
  'blswi': 'After Brügge',
  'blswv': 'After Brügge',
  'afla': 'After Brügge',
  'aflce': 'After Brügge',
  'aflcn': 'After Brügge',
  'aflec': 'After Brügge',
  'plai': 'After Brügge',
  'plce': 'After Brügge',
  'plcn': 'After Brügge',
  'plee': 'After Brügge',
  'plpe': 'After Brügge'
};
window.songImages = { 'acn': 'https://skydevaaben.no/assets/og/ba467427-ce13-4f29-a348-c1470180a425-1.jpg', 'bace': 'https://skydevaaben.no/assets/og/born-again-ab-cover.jpg', 'bacn': 'https://skydevaaben.no/assets/og/born-again-ab-cover.jpg', 'baswi': 'https://skydevaaben.no/assets/og/born-again-ab-cover.jpg', 'blcn': 'https://skydevaaben.no/assets/og/bleeding-ab-cover.jpg', 'blswi': 'https://skydevaaben.no/assets/og/bleeding-ab-cover.jpg', 'blswv': 'https://skydevaaben.no/assets/og/bleeding-ab-cover.jpg', 'fwaf': 'https://skydevaaben.no/assets/og/fire-album-cover.jpg', 'glp': 'https://skydevaaben.no/assets/og/glasspeople-cover-3000-sharpened.jpg', 'lwy': 'https://skydevaaben.no/assets/og/lost-song-cover.jpg', 'plai': 'https://skydevaaben.no/assets/og/please-ab-cover-1.jpg', 'plce': 'https://skydevaaben.no/assets/og/please-ab-cover-1.jpg', 'plcn': 'https://skydevaaben.no/assets/og/please-ab-cover-1.jpg', 'plee': 'https://skydevaaben.no/assets/og/please-ab-cover-1.jpg', 'plpe': 'https://skydevaaben.no/assets/og/please-ab-cover-1.jpg', 'aflcn': 'https://skydevaaben.no/assets/og/low-ab-cover.jpg', 'aflce': 'https://skydevaaben.no/assets/og/low-ab-cover.jpg', 'afla': 'https://skydevaaben.no/assets/og/low-ab-cover.jpg', 'aflec': 'https://skydevaaben.no/assets/og/low-ab-cover.jpg', 'skdh': 'https://skydevaaben.no/assets/og/digital-heartbeat-cover.jpg' };
window.slugs = [
  'fbacn1',
  'fbacn2',
  'fbacn3',
  'fbafla1',
  'fbaflce1',
  'fbaflcn1',
  'fbaflec1',
  'fbbace1',
  'fbbacn1',
  'fbbaswi1',
  'fbblcn1',
  'fbblcn2',
  'fbblswi1',
  'fbblswi2',
  'fbblswv1',
  'fbblswv2',
  'fbfwaf1',
  'fbglp1',
  'fbglp2',
  'fbglp3',
  'fbglp4',
  'fblwy1',
  'fblwy2',
  'fblwy3',
  'fbplai1',
  'fbplce1',
  'fbplcn1',
  'fbplee1',
  'fbplpe1',
  'fbskdh1',
  'igacn1',
  'igacn2',
  'igacn3',
  'igafla1',
  'igaflce1',
  'igaflcn1',
  'igaflec1',
  'igbace1',
  'igbacn1',
  'igbaswi1',
  'igblcn1',
  'igblcn2',
  'igblswi1',
  'igblswi2',
  'igblswv1',
  'igblswv2',
  'igfwaf1',
  'igglp1',
  'igglp2',
  'igglp3',
  'igglp4',
  'iglwy1',
  'iglwy2',
  'iglwy3',
  'igplai1',
  'igplce1',
  'igplcn1',
  'igplee1',
  'igplpe1',
  'igskdh1',
  'ttacn1',
  'ttacn2',
  'ttacn3',
  'ttafla1',
  'ttaflce1',
  'ttaflcn1',
  'ttaflec1',
  'ttbace1',
  'ttbacn1',
  'ttbaswi1',
  'ttblcn1',
  'ttblcn2',
  'ttblswi1',
  'ttblswi2',
  'ttblswv1',
  'ttblswv2',
  'ttfwaf1',
  'ttglp1',
  'ttglp2',
  'ttglp3',
  'ttglp4',
  'ttlwy1',
  'ttlwy2',
  'ttlwy3',
  'ttplai1',
  'ttplce1',
  'ttplcn1',
  'ttplee1',
  'ttplpe1',
  'ttskdh1',
  'ytacn1',
  'ytacn2',
  'ytacn3',
  'ytafla1',
  'ytaflce1',
  'ytaflcn1',
  'ytaflec1',
  'ytbace1',
  'ytbacn1',
  'ytbaswi1',
  'ytblcn1',
  'ytblcn2',
  'ytblswi1',
  'ytblswi2',
  'ytblswv1',
  'ytblswv2',
  'ytfwaf1',
  'ytglp1',
  'ytglp2',
  'ytglp3',
  'ytglp4',
  'ytlwy1',
  'ytlwy2',
  'ytlwy3',
  'ytplai1',
  'ytplce1',
  'ytplcn1',
  'ytplee1',
  'ytplpe1',
  'ytskdh1'
];